#ifndef ERROR_CODE_H
#define ERROR_CODE_H

// Error code
typedef enum
{
	SUCCESS,
	FAILURE = 0xFFFFFFFF,

	// 0x0000000X
	PARAMETER_1 = 0x00000001,
	PARAMETER_2,
	PARAMETER_3,
	PARAMETER_4,
	PARAMETER_5,
	PARAMETER_6,
	PARAMETER_7,
	PARAMETER_8,
	PARAMETER_9,
	PARAMETER_A,
	PARAMETER_B,
	PARAMETER_C,
	PARAMETER_D,
	PARAMETER_E,
	PARAMETER_N = 0x0000000F,

	// 0x000000XX
	PARAMETER_ERROR 		= 0x00000010,
	PARAMETER_NULL			= 0x00000020,
	PARAMETER_NOT_NULL		= 0x00000030,
	PARAMETER_EMPTY			= 0x00000040,
	PARAMETER_TYPE_ERROR	= 0x00000050,
	PARAMETER_SIZE_OVERFLOW	= 0x00000060,

	// 0x00000XXX
	ELEMENT_NULL_IN_CONTAINER = 0x00000100,
	NO_ELEMENT_IN_CONTAINER,
	ELEMENT_INSERT_FAILURUE,
	ELEMENT_ERROR_IN_CONTAINER,
	ELEMENT_EXIST_IN_CONTAINER,
	STRING_NULL,
	SIZE_OVERFLOW,
	TYPE_ERROR,
	SIZE_FIELD_ERROR,
	FROBID_USE,
	DEFINE_VARIABLE_FAILURE,
	SEND_FAILUE,
	XML_INITIALIZE_ERROR,
	XML_UNINITIALIZE_ERROR,
	XML_LOADER_ERROR,
	XML_TERMINATE_ERROR,
	XML_INVALID_ELEMENT,

	VARIABLE_OPERATION_ERROR,
	OPERATOR_OPERAITON_ERROR,

	FILE_READ_ERROR,
	FILE_WRITE_ERROR,
	FILE_DELETE_ERROR,
	SYS_CALL_ERROR,

	FIELD_TYPE_ERROR,
	FIELD_DATA_NULL,
	FIELD_INDEX_ERROR,
	FIELD_SIZE_OVERLOADED,

	WINDOW_IS_NOT_EXIST,
	WINDOW_CREATE_ERROR,
	WINDOW_DATA_ERROR,
} error_code;

#endif // ERROR_CODE_H
